# Generated by Django 3.1.3 on 2020-11-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0002_auto_20201121_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espout',
            old_name='statusOfPin',
            new_name='status',
        ),
        migrations.AddField(
            model_name='espout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
