# Generated by Django 3.1.3 on 2020-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0004_espsensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ESPmodulesIN',
        ),
        migrations.AlterField(
            model_name='espout',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='espout',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
