# Generated by Django 3.1.3 on 2020-11-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0006_user_espoutputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espsensor',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='espsensor',
            name='pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='ESPoutputs',
            field=models.ManyToManyField(to='SH.ESPOut'),
        ),
    ]
