# Generated by Django 3.1.3 on 2020-11-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0007_auto_20201122_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ESPsensor',
            field=models.ManyToManyField(to='SH.ESPSensor'),
        ),
    ]
