# Generated by Django 3.1.3 on 2020-11-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0008_user_espsensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ESPoutputs',
            field=models.ManyToManyField(blank=True, null=True, to='SH.ESPOut'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ESPsensor',
            field=models.ManyToManyField(blank=True, null=True, to='SH.ESPSensor'),
        ),
    ]
