# Generated by Django 3.1.3 on 2020-11-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0009_auto_20201122_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espsensor',
            name='value',
            field=models.IntegerField(blank=True),
        ),
    ]
