# Generated by Django 3.1.3 on 2020-11-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0010_auto_20201122_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espout',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
