# Generated by Django 3.1.3 on 2020-12-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0012_auto_20201225_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
