# Generated by Django 3.1.3 on 2020-12-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0013_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=10),
        ),
    ]
