# Generated by Django 3.1.3 on 2020-12-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0015_auto_20201226_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ESPoCount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ESPsCount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
