# Generated by Django 3.1.3 on 2021-01-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0016_auto_20201226_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='espsensor',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
