# Generated by Django 3.1.3 on 2021-01-16 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0018_auto_20210116_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='espout',
            name='maxValue',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='espout',
            name='minValue',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='espout',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SH.espsensor'),
        ),
    ]
