# Generated by Django 3.1.3 on 2021-01-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0020_espout_currentvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espout',
            name='maxValue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='espout',
            name='minValue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
