# Generated by Django 3.1.3 on 2021-01-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SH', '0021_auto_20210125_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espout',
            name='maxValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='espout',
            name='minValue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
